### ISSUE TITLE
Deprecated selector in `proto-repl\styles\proto-repl.less`

### ISSUE THREAD

**Issue by alombide** [jasongilman/proto-repl#226] opened 2017-01-30 14:33 UTC
In `proto-repl\styles\proto-repl.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `:host atom-text-editor .highlight.block-execution .region,
atom-text-editor atom-text-editor .highlight.block-execution .region,
atom-text-editor::shadow atom-text-editor .highlight.block-execution .region` => `:host atom-text-editor .highlight.block-execution .region,
atom-text-editor atom-text-editor .highlight.block-execution .region,
atom-text-editor.editor atom-text-editor .highlight.block-execution .region`

* `:host .highlights .block-execution .region,
atom-text-editor .highlights .block-execution .region,
atom-text-editor::shadow .highlights .block-execution .region` => `:host .highlights .block-execution .region,
atom-text-editor .highlights .block-execution .region,
atom-text-editor.editor .highlights .block-execution .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mrattner** [comment] 2017-02-26 08:53
This is a duplicate of #221. I think most people who noticed this (including me) did so because of the deprecation-cop package. So it's a very minor issue, but disconcerting to see the "!" in the status bar :)

**Comment by draeath** [comment] 2017-03-01 20:22
Well, it's a minor issue *now.*

It'll cease to be minor when this little bit at the end happens: "Automatic translation of selectors will be removed in a few release cycles to minimize startup time."

**Comment by Quandrant** [comment] 2017-03-11 22:58
Thank you-- I was just about to report this issue. It's a bit disconcerting to see the exclamation mark. :P

**Comment by jasongilman** [comment] 2017-03-16 00:59
Duplicate of #221 which is fixed

**Closed as completed by jasongilman** 2017-03-16 00:59 UTC
