### ISSUE TITLE
proto-repl cannot be loaded since it depends on oniguruma

### ISSUE THREAD

**Issue by veer66** [jasongilman/proto-repl#143] opened 2016-08-15 10:19 UTC
proto-repl cannot be loaded since it depends on oniguruma on Atom 1.9.8 on Ubuntu 16.04.

![onig_atom](https://cloud.githubusercontent.com/assets/370688/17661919/4a9ff15e-630c-11e6-9082-75c851d04278.png)

**Comment by carocad** [comment] 2016-08-15 11:21
this is a possible duplicate of #136. Please consider closing it if you think so.

Also, would you mind telling us if you have a developer version of proto-repl installed? or is it just the official stable one?

**Comment by jasongilman** [comment] 2016-08-17 02:36
@veer66 you should be able to fix this by clicking the rebuild packages button.

**Closed as completed** 2016-08-19 00:05 UTC
