### ISSUE TITLE
Ratios are displaying as floating in protorepl

### ISSUE THREAD

**Issue by jreighley** [jasongilman/proto-repl#130] opened 2016-07-27 21:14 UTC
In my lein repl from the command line:

protoratio.core=> (def piishness (/ 44 14))
# 'protoratio.core/piishness

protoratio.core=> piishness
22/7

![image](https://cloud.githubusercontent.com/assets/3386478/17191851/d2aca9cc-5400-11e6-952f-c7525732a821.png)

When I do the same thing in my protorepl:

(def piishness (/ 44 14))
protoratio.core=>
# 'protoratio.core/piishness

piishness
protoratio.core=>
3.142857142857143

![image](https://cloud.githubusercontent.com/assets/3386478/17192390/1a3ba0c0-5403-11e6-9ff3-d9d8b94770ca.png)

It also renders  the float numbers on the inline results.   It does it when connected to the nRepl port from the exiting lein repl (that is functioning correctly) as well.

**Comment by jasongilman** [comment] 2016-07-27 23:44
Thanks for the detailed bug report. The image helps a lot. I'm still really stumped here as I can't reproduce it. Would it be possible for you to share the project you created? Could you tell me what version of Proto REPL you're using. 

I know about the inline problem but the problem in the REPL I haven't seen before. I tried setting things up in all the same ways as you can see in the picture below. Could you also try running `(type (/ 44 7))` in the REPL?

<img width="1147" alt="clojure_repl_ __users_jason_protoratio_and_untitled_ __users_jason_work_github_workspace_proto-repl" src="https://cloud.githubusercontent.com/assets/192983/17196423/96ccff92-5432-11e6-8845-5d8d3362be22.png">

**Comment by jreighley** [comment] 2016-07-27 23:57
version 1.3.3  

```
(type (/ 44 14))
user=>
clojure.lang.Ratio
```

I installed on atom another machine, and installed protorepl as the only Package and the issue did not occur.  I am wondering if it is a conflict with one of the other rendering aids.

**Comment by jreighley** [comment] 2016-07-28 03:40
Another interesting tidbit:  

![image](https://cloud.githubusercontent.com/assets/3386478/17200441/1d7a6fd2-543a-11e6-9682-35da7b955dc7.png)

**Comment by jreighley** [comment] 2016-07-28 04:25
I figured out how to replicate and de-replicate the issue.   

If the "Auto Pretty Print" feature is checked, the ratio displays as floaty numbers.  If it is unchecked It displays as the ratio that is it's true self 22/7

This toggles the behavior on my naughty machine -- Unfortunately I don't have access to my well behaved machine at this hour -- so I cannot check to see if the toggle works there as well..

**Comment by jasongilman** [comment] 2016-07-28 11:08
That's great. You figured out the problem. The auto pretty print feature uses a ClojureScript library to print it. That means the the differences in ClojureScript are going to impact printing.

**Comment by jasongilman** [comment] 2016-08-19 00:11
This is a duplicate of #77

**Closed as completed by jasongilman** 2016-08-19 00:11 UTC

**Comment by kmob** [comment] 2018-06-29 22:47
Jason - First, this project is great work and greatly appreciated. 

I am going to use Atom/Proto-Repl to teach my kids Clojure this summer and immediately ran across the ratios/doubles issue. 

It would be helpful if you placed a note about the consequences of enabling "auto pretty print" in your recommended setup page. The recommended setup was great for getting the environment working but we were pretty confused going through the type basics.

Thanks for everything you are doing!

Kevin
