### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by nimaai** [jasongilman/proto-repl#90] opened 2016-04-05 08:07 UTC
Hi,

Autocompletion menu won't appear. In the console the following exception is being thrown:

`NullPointerException java.util.regex.Matcher.getTextLength (Matcher.java:1283)` at `completion-provider.coffee:80`

I am attaching the atom stack trace.

The versions of the environment are as follows:
OSX 10.11.4, Atom 1.6.2, Proto-Repl 1.1.6,  autocomplete-plus  2.25.0

![screen shot 2016-04-04 at 09 46 14](https://cloud.githubusercontent.com/assets/3205913/14275178/130b5caa-fb16-11e5-97b2-bae4cf180d8c.png)

**Comment by jasongilman** [comment] 2016-04-05 23:57
Can you log the code being executed on line 76? Could you also put the project.clj file you're using in this issue or link to it?

**Comment by nimaai** [comment] 2016-04-06 07:54
![screen shot 2016-04-06 at 09 53 53](https://cloud.githubusercontent.com/assets/3205913/14309558/7f726498-fbdd-11e5-81ed-17febbd43f58.png)

https://github.com/jasongilman/proto-repl-demo/blob/master/project.clj

**Comment by jasongilman** [comment] 2016-04-06 22:46
I tried the exact same thing as you and it worked. I got the same exact code. 

This is really stumping me. Do you have anything in a ~/.lein/profiles.clj file?

Can you try running `(System/getProperty "java.class.path")` in the REPL and paste the results here. I'm looking to see if somehow you're using some other older version or something. You should see something like `....m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar` in the results.

**Comment by nimaai** [comment] 2016-04-07 07:12
Your suspicion is correct. The problem is with my `~/.lein/profiles.clj`:

``` clojure
{:user {:plugins [[cider/cider-nrepl "0.8.2"]
                  [lein-ancient "0.6.7"]
                  [lein-pprint "1.1.1"]]}}
```

Some incompatible plugin or version?

**Comment by jasongilman** [comment] 2016-04-10 19:05
Sorry I haven't gotten back to this in a couple days. The problem is cider-nrepl refers to complement as well and that version of cider-nrepl is probably referring to an old version of complement which will override what's in a project dependency. If you remove that dependency or update to a newer version it will probably fix this issue.

**Comment by nimaai** [comment] 2016-04-10 20:48
Yes, the issue is fixed by removing the cider-nrepl dependency. Thanks.

**Comment by ghost** [comment] 2016-04-13 13:11
I've been getting the same issue, but I'm getting it on all projects. So if you do `lein new app` and get the most barebones project.clj I'm still getting the null pointer exception when it tries to do the autocomplete.

**Comment by jasongilman** [comment] 2016-04-24 19:13
@kingoftheknoll Are you seeing the exception in the REPL itself? Have you checked for a dependency on cider-nrepl in a ~/.lein/profiles.clj file?

**Comment by jasongilman** [comment] 2016-05-14 23:18
Closing this since it's related to incorrect dependencies.

**Closed as completed by jasongilman** 2016-05-14 23:18 UTC
Labels: bug

**Comment by tosh** [comment] 2016-12-23 15:13
I just wanted to mention that I ran into the same issue (autocompletion not working) and also was able to solve the problem by removing my `~/.lein/profiles.clj` file (which I created by following "Clojure for the Brave and True").

Would it make sense to add some info/hint to the proto-repl readme in the section about autocompletion?
