### ISSUE TITLE
Ratios displaying as float

### ISSUE THREAD

**Issue by russellpipal** [jasongilman/proto-repl#158] opened 2016-08-25 22:01 UTC
I'm new to Clojure development, but ratios don't seem to be working properly in my proto-repl. In lein, 1/2 returns 1/2, but in proto-repl 1/2 returns 0.5.

**Comment by carocad** [comment] 2016-08-25 22:12
this is a duplicate of #77

**Comment by jasongilman** [comment] 2016-08-25 22:47
Check out the details on #77 to understand why it's happening. You can disable automatic pretty printing to stop that in the REPL.

**Closed as completed by jasongilman** 2016-08-25 22:47 UTC
